### PR TITLE
Create Marvel Endpoints

### PR DESCRIPTION
**Pull request by PaulVagner**
All endpoints added with descriptions

### CODE REVIEW

**Comment by joalbright** [comment]
+1

**Comment by PaulVagner** [comment]
Wasn't sure how to handle line 39 & 100 ..... so i just stuck with the
standard setup....

If you want me to change anything or edit anything you can see (This time I
made sure to check and double-check before sending to you), please let me
know .....

Thank You

P.S. So..... about them StarWars?!?!....... :)

[image: Inline image 4]
[image: Inline image 5]

**Comment by PaulVagner** [comment]
Hey dude..... working... well... at least trying to figure out this
shindig.....


could you look at it and TELL ME what I'm doing wrong....


Thank You

**Comment by joalbright** [comment]
Not seeing the images. Can you try to resend?

Jo

**Comment by PaulVagner** [comment]
ok[image: Inline image 1]



I also updated the Uber API..... sent you the info yesterday....

**Pull request merged**
